### PR TITLE
1357/do not mutate endpoint method options

### PR DESCRIPTION
**Pull request by drdoom1211**
-----
[View rendered README.md](https://github.com/drdoom1211/rest.js/blob/1357/do-not-mutate-endpoint-method-options/README.md)
[View rendered docs/README.md](https://github.com/drdoom1211/rest.js/blob/1357/do-not-mutate-endpoint-method-options/docs/README.md)
[View rendered docs/src/pages/api/00_usage.md](https://github.com/drdoom1211/rest.js/blob/1357/do-not-mutate-endpoint-method-options/docs/src/pages/api/00_usage.md)
[View rendered docs/src/pages/api/01_authentication.md](https://github.com/drdoom1211/rest.js/blob/1357/do-not-mutate-endpoint-method-options/docs/src/pages/api/01_authentication.md)
[View rendered docs/src/pages/api/02_introduction.md](https://github.com/drdoom1211/rest.js/blob/1357/do-not-mutate-endpoint-method-options/docs/src/pages/api/02_introduction.md)
[View rendered docs/src/pages/api/03_request_formats.md](https://github.com/drdoom1211/rest.js/blob/1357/do-not-mutate-endpoint-method-options/docs/src/pages/api/03_request_formats.md)
[View rendered docs/src/pages/api/04_custom_requests.md](https://github.com/drdoom1211/rest.js/blob/1357/do-not-mutate-endpoint-method-options/docs/src/pages/api/04_custom_requests.md)

### CODE REVIEW

**Comment by wolfy1339** [comment]
Hello @drdoom1211, it looks like the git history of this branch is screwed up. Are you good enough with git to fix it? If not, just resubmit the patch applied on the latest version of the master branch.

**Comment by wolfy1339** [comment]
This patch  has already been submitted and merged. Any reason you are submitting it again?

**Comment by drdoom1211** [comment]
No I have no idea what I’m doing. Unfortunately I needed to do something
since ny husband is a tech genius and has spyware on everything. I can see
it but can’t trace it to him so until I can he plays dumb. I would
appreciate any advice.

**Comment by drdoom1211** [comment]
No again no clue if it Alene’s or not I guess I assumed it didn’t

**Pull request closed without merging**
