### PR TITLE
feat: v21

### PR DESCRIPTION
**Pull request by wolfy1339**
BREAKING CHANGE: package is now ESM

### CODE REVIEW

**Comment by wolfy1339** [comment]
It seems that the test is failing because of a trailing slash (`/`) missing

**Comment by wolfy1339** [comment]
@octokit/js Is anyone able to figure out how to get the test passing?

Is there a way to get `@octokit/endpoint` to ignore the trailing `/` for the `GET /repos/{owner}/{repo}/contents/{path}` endpoint, if path is empty

**Comment by oscard0m** [comment]
> @octokit/js Is anyone able to figure out how to get the test passing?
> 
> Is there a way to get `@octokit/endpoint` to ignore the trailing `/` for the `GET /repos/{owner}/{repo}/contents/{path}` endpoint, if path is empty

I'm going to take a look into this. I'll keep you posted.

**Comment by oscard0m** [comment]
> > @octokit/js Is anyone able to figure out how to get the test passing?
> > Is there a way to get `@octokit/endpoint` to ignore the trailing `/` for the `GET /repos/{owner}/{repo}/contents/{path}` endpoint, if path is empty
> 
> I'm going to take a look into this. I'll keep you posted.

### The Problem (in `test/scenarios/get-content.test.ts`)

I'm focusing on the tests failing for `test/scenarios/get-content.test.ts`. I will add a new comment for the other test failing.

The error prompted is the following one ([complete logs here](https://github.com/octokit/rest.js/actions/runs/8624350069/job/23639182867?pr=413)):

```bash
HttpError: Unknown error: {"error":"GET /repos/octokit-fixture-org/hello-world/contents does not match next fixture: GET /repos/octokit-fixture-org/hello-world/contents/","detail":{"pending":["GET [https://fixtures-987ffyc5v8n.api.github.com:443/repos/octokit-fixture-org/hello-world/contents/](https://fixtures-987ffyc5v8n.api.github.com/repos/octokit-fixture-org/hello-world/contents/)","GET [https://fixtures-987ffyc5v8n.api.github.com:443/repos/octokit-fixture-org/hello-world/contents/README.md](https://fixtures-987ffyc5v8n.api.github.com/repos/octokit-fixture-org/hello-world/contents/README.md)"]}}
```

### The root cause

The line swallowing the ending `/` for the URL requested is this one https://github.com/octokit/endpoint.js/blob/fdbc2643b75d7f291eba3b1cda6428946093d778/src/util/url-template.ts#L197

This change was introduced in https://github.com/octokit/endpoint.js/pull/455 to cover use cases like:

| Request | Response |
|--------|--------|
| `/repos/OWNER/REPO/branches` | 200 |
| `/repos/OWNER/REPO/branches/` | 404 | 

But, `/repos/OWNER/REPO/contents/PATH` work with and without `/`, so we should probably support both [^1].

| Request | Response |
|--------|--------|
| `/repos/octokit/endpoint.js/contents` | 200 |
| `/repos/octokit/endpoint.js/contents/` | 200 |
| `/repos/octokit/endpoint.js/contents/test` | 200 |
| `/repos/octokit/endpoint.js/contents/test/` | 200 |

This mismatch comes when we compare the requested URL (with no ending `/`) and the expected from `@octokit/fixtures` (with ending `/`):
https://github.com/octokit/fixtures/blob/5aa66e46e3f3475c4c1eb521cd402dfd85091b52/scenarios/api.github.com/get-content/normalized-fixture.json#L5

We should probably improve the logic we have in place in `@octokit/endpoints` but I would like to hear your thoughts on this @octokit/js.

[^1]: [Apparently in the past the trailing `/` was not working](https://github.com/octokit/endpoint.js/pull/455#issuecomment-1781428483) but seems that [it was escalated](https://github.com/octokit/endpoint.js/pull/455#issuecomment-1781455546) and now it's working.

**Comment by oscard0m** [comment]
### The Problem (in `test/scenarios/get-archive.test.ts`)

The error prompted is the following one ([complete logs here](https://github.com/octokit/rest.js/actions/runs/8624350069/job/23639182867?pr=413)):

```bash
HttpError: Unknown error: {"error":"Nock: No match for request","detail":{"expected":{"method":"GET","url":"https://fixtures-r9di1toxolb.api.github.com/repos/octokit-fixture-org/get-archive/tarball/main","headers":{"accept-encoding":"gzip, deflate","sec-fetch-mode":"cors","accept-language":"*","authorization":"token 0000000000000000000000000000000000000001","user-agent":"octokit-rest.js/0.0.0-development octokit-core.js/6.1.2 Node.js/20.12.1 (darwin; x64)","accept":"application/vnd.github.v3+json","connection":"close","host":"fixtures-r9di1toxolb.api.github.com"}}}}
```

### The root cause
I've been debugging a bit but did not found the root cause yet. I will keep checking. It's the only fixture which uses `302` as status response. Maybe it has something to do with that. What I can say is the issue is unrelated to the one with `get-content`.

**Comment by wolfy1339** [comment]
I have skipped the tests that are failing for now. This PR should be ready to go

**Review by gr2m — APPROVED** [review]

**Pull request merged**
